export const AUDIT_ACTIONS = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  RETRY: "RETRY",
  COMPLETE: "COMPLETE",
  FAIL: "FAIL",
} as const;

export type AuditAction =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ENTITY_TYPES = {
  PROPERTY: "PROPERTY",
  PROPERTY_CODES: "PROPERTY_CODES",
  PROPERTY_DOCUMENT: "PROPERTY_DOCUMENT",
  PROPERTY_PHOTO: "PROPERTY_PHOTO",
  PROPERTY_AMENITY: "PROPERTY_AMENITY",
  AMENITY: "AMENITY",
  HOUSE_RULE: "HOUSE_RULE",
  CHECKIN_CONFIGURATION: "CHECKIN_CONFIGURATION",
  BOOKING: "BOOKING",
  GUEST: "GUEST",
  OWNER: "OWNER",
  TASK: "TASK",
  CLEANING_TASK: "CLEANING_TASK",
  CHECKOUT_TASK: "CHECKOUT_TASK",
  DOCUMENT_TASK: "DOCUMENT_TASK",
  OPERATIONAL_TASK: "OPERATIONAL_TASK",
  FINANCE_FORMULA: "FINANCE_FORMULA",
  FINANCE_REPORT: "FINANCE_REPORT",
  OCR: "OCR",
} as const;

export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];