export const INTEGRATION_ERROR_CODES = {
  INVALID_CURSOR: "INVALID_CURSOR",
  INVALID_LIMIT: "INVALID_LIMIT",
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",
  INVALID_WEBHOOK_PAYLOAD: "INVALID_WEBHOOK_PAYLOAD",
  RATE_LIMITED: "RATE_LIMITED",
  NETWORK_ERROR: "NETWORK_ERROR",
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type IntegrationErrorCode =
  (typeof INTEGRATION_ERROR_CODES)[keyof typeof INTEGRATION_ERROR_CODES];